### ISSUE TITLE
MacOS build?

### ISSUE THREAD

**Issue by lawendel** [kkonradpl/xdr-gtk#5]
Hi, I found a reference to OSX compatibility on your site, but I wonder if there's any hint around of a successful MacOS build? I can't find any dependencies list, but I assume I have to build GTK-OSX (here on Github) first?
Thanks for any directions!

Andy

**Comment by kkonradpl** [comment]
Hello, the OS X build was prepared by one of users almost 10 years ago and I have no information how it was done. I also believe that the build process probably has changed significantly since 2014. I have never used OS X, so it's hard for me to say anything.

You should follow the official guide: https://wiki.gnome.org/Projects/GTK/OSX/Building

BTW, currently I'm working on GTK3 version, it should be available soon.

**Comment by lawendel** [comment]
Thank you Konrad! Aside from GTK, is there any other Linux dependency one should be aware of?

Andy

**Comment by kkonradpl** [comment]
No, there are no other dependencies. I've just pushed a commit of the GTK+ 3 version.

**Comment by kkonradpl** [comment]
One more thing should be clarified, the antenna radiation pattern tool has been removed from the new GTK+ 3 version.
XDR-GTK is now integrated with antpatt software: https://github.com/kkonradpl/antpatt
You will need it to make the antenna pattern function working. Antpatt has more dependencies (GSL, JSON-C, zlib) as listed in the README.
